events { worker_connections 1024; }
http {
    include /etc/nginx/mime.types;
    server {
        listen 80;
        server_name cloud.nexpartner.lab;
        server_tokens off; # M1-L01: Proteção

        location / {
            proxy_pass http://nexpartner-app:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # M1-L14: Trust Abuse
        }
        location ~ /\.git { deny all; } # M1-L07: Proteção configurada
    }
}
