events {}
http {
    server { listen 80; server_name blog.signaldesk.lab; location / { proxy_pass http://signaldesk:80; } }
    server { listen 80; server_name cloud.nexpartner.lab; location / { proxy_pass http://nexpartner:8080; } }
    server { listen 80; server_name ops.internal.lab; location / { proxy_pass http://pulseops:8080; } }
    server { listen 80; server_name sso.helix.lab; location / { proxy_pass http://helix:8080; } }
    server { listen 80; server_name shop.asterion.lab; location / { proxy_pass http://asterion:8080; } }
    server { listen 80; server_name finance.ledgerflow.lab; location / { proxy_pass http://ledgerflow:8080; } }
}
