worker_processes auto;
events { worker_connections 1024; }
http {
    resolver 127.0.0.11 valid=30s;
    include /etc/nginx/mime.types;
    server {
        listen 80;
        server_name cloud.nexpartner.lab;
        server_tokens on;

        location / { set $target_core nexpartner-app; proxy_pass http://$target_core:8080; }
        location /ops/ { proxy_pass http://pulseops:8080/; } # Ajustado para porta interna Spring
        location /finance/ { proxy_pass http://ledgerflow:8000/; }
        location /market/ { proxy_pass http://asterion:3001/; }
        location /identity/ { proxy_pass http://helix:3000/; }
        location /legacy/ { proxy_pass http://signaldesk:80/; }
        
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
