server {
    listen 80;
    server_name cloud.nexpartner.lab;
    
    # M1-L01: Expondo versão do Nginx (Leads to fingerprinting)
    server_tokens on;

    # M1-L11: Sugerindo subdomínios em headers customizados (Staging Discovery)
    add_header X-Staging-Node "dev-mesh.nexpartner.lab";
    add_header X-Powered-By "Node/20.20.1";

    # M1-L12/L13: Falta de HSTS e Mixed Content é permitida aqui
    # add_header Strict-Transport-Security "max-age=0"; # Removido para lab

    location /api/v1/ {
        proxy_pass http://nexpartner-app:8080;
        # M1-L14: Trust no header X-Forwarded-For (Vulnerável)
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
    }

    location / {
        root /app/dist;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
