worker_processes auto;
events { worker_connections 1024; }
http {
    include /etc/nginx/mime.types;
    server {
        listen 80;
        server_name cloud.nexpartner.lab;

        location / {
            proxy_pass http://nexpartner-app:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Ajustes de timeout para evitar 504 durante o crash do lab
            proxy_connect_timeout 5s;
            proxy_read_timeout 10s;
        }
    }
}
